import { storiesType } from "../types"
export const stories:storiesType[] = [
    {
        id:1,
        firstName:'Aman',
        profileImage:require('../assets/images/default_profile.png')
    },
    {
        id:2,
        firstName:'Pratham',
        profileImage:require('../assets/images/default_profile.png')
    },
    {
        id:3,
        firstName:'Sam',
        profileImage:require('../assets/images/default_profile.png')
    },
    {
        id:4,
        firstName:'John',
        profileImage:require('../assets/images/default_profile.png')
    },
    {
        id:5,
        firstName:'Yash',
        profileImage:require('../assets/images/default_profile.png')
    },
    {
        id:6,
        firstName:'OM',
        profileImage:require('../assets/images/default_profile.png')
    },
    {
        id:7,
        firstName:'Joe',
        profileImage:require('../assets/images/default_profile.png')
    },
    {
        id:8,
        firstName:'Mark',
        profileImage:require('../assets/images/default_profile.png')
    },
    {
        id:9,
        firstName:'Toni',
        profileImage:require('../assets/images/default_profile.png')
    }
]